### ISSUE TITLE
new WHM.Client doesn't work

### ISSUE THREAD

**Issue by sudodaksh** [ihadeed/node-whm#11]
TypeError: WHM.Client is not a constructor

**Comment by ihadeed** [comment]
Can you provide steps to reproduce the issue you're having?

**Comment by sudodaksh** [comment]
I Imported the module and created it's new instance as a client but when I do so the console provides me an error that says, It's not a constructor.
`var WHM = require("node-whm/dist");
 var client = new WHM.Client({
// Details here.
});
`

**Comment by ihadeed** [comment]
This should be resolved now. Please update to version `0.2.0` and let me know if you're still having issues.

Thanks for pointing the issue out.

**Comment by sudodaksh** [comment]
Thanks for fixing the issue 👍
